### ISSUE TITLE
shellenv missing

### ISSUE THREAD

**Issue by ucirello** [alvarolm/GoGuru#1]
After installation it doesn't work because shellenv package is missing:

```
import sublime, sublime_plugin, subprocess, time, re, os, subprocess, sys, shellenv
ImportError: No module named 'shellenv'
```

**Comment by alvarolm** [comment]
thanks mate !, it should be fixed

https://github.com/alvarolm/GoGuru/commit/947034defe67c9369ce8a64eb528a88e077f8e07
https://github.com/alvarolm/GoGuru/commit/ab69ee88d59d31ebe3992903bfbe816fb30ff5f9
https://github.com/alvarolm/GoGuru/commit/87e8d4198b79ccaf6e4aae2dd5ce489585c402ad

please tell me if its working for you and I'll close this one 
:)

**Comment by ucirello** [comment]
Updated using git. Still fails

```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 78, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "/Users/uldericofilho/Library/Application Support/Sublime Text 3/Packages/GoGuru/goGuru.py", line 11, in <module>
    import sublime, sublime_plugin, subprocess, time, re, os, subprocess, sys, shellenv
ImportError: No module named 'shellenv'
```

I do see files in `dep/` though.

**Comment by alvarolm** [comment]
fixed https://github.com/alvarolm/GoGuru/commit/cdf94d284de08bcac6cd3cd8812211a747ff9afe
they are https://github.com/alvarolm/GoGuru/tree/master/dep/shellenv

please try again :)

**Comment by ucirello** [comment]
Problem fix. Another bug remains, opening a new issue.

**Comment by alvarolm** [comment]
hooray ! this one is over :)
I'll watching for the new issue, thanks !
