### ISSUE TITLE
The plugin is not working for me

### ISSUE THREAD

**Issue by jostyee** [alvarolm/GoGuru#18]
Env:
OS X 10.11
Sublime Text 3 Build 3113

My problem:
Pressing down the default hotkey "Ctrl+shift+g" would make the current line blinks without popping up the guru window. Console output:

```
Unable to open /Users/me/Library/Application Support/Sublime Text 3/Packages/GoGuru/Default.sublime-settings
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 231, in run_callback
    expr()
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 327, in <lambda>
    run_callback('on_activated', callback, lambda: callback.on_activated(v))
  File "trailing_spaces in /Users/me/Library/Application Support/Sublime Text 3/Installed Packages/TrailingSpaces.sublime-package", line 419, in on_activated
  File "trailing_spaces in /Users/me/Library/Application Support/Sublime Text 3/Installed Packages/TrailingSpaces.sublime-package", line 440, in freeze_last_version
  File "./python3.3/codecs.py", line 896, in open
FileNotFoundError: [Errno 2] No such file or directory: '/Users/me/Library/Application Support/Sublime Text 3/Packages/GoGuru/Default.sublime-settings'
```

GoGuru plugin didn't create the corresponding directory on my system, tried to reinstall several times without luck.

**Comment by alvarolm** [comment]
sorry for the delay, could you please paste the logs here (copy the lines from the console that start with 'GoGuru:') ?

They look like this:

```
GoGuru: ('debug:', False)
GoGuru: ('use_golangconfig', False)
GoGuru: ('version:', '0.1.7')
```

**Comment by jostyee** [comment]
``` shell
GoGuru: ('debug:', False)
GoGuru: ('use_golangconfig', False)
GoGuru: ('version:', '0.1.7')
```

It's weird that I'd set `"goguru_debug": true` in user settings but seems not working.

When using cmd+shift+p to invoke command, the output halt only shows:

> Running guru definition command...

forever. guru tool installed & in $PATH already.

**Comment by alvarolm** [comment]
**remove or disable the 'TrailingSpaces' package and try again**

with respect to the settings issue, should be fixed in the version **0.1.8**, I have been under a lot of work so sorry for the delay again.

I recommend you to first delete the current GoGuru package using the sublime package control and wait for the version **0.1.8** to be available at the package control repo, (check here to see if has been updated https://packagecontrol.io/packages/GoGuru under Details > version) then install it again.

https://github.com/alvarolm/GoGuru/commit/d3d7e1cf1c00c16670790a6709ece376bd7e1ea6
https://github.com/alvarolm/GoGuru/commit/2768dfd61db8c70c1eda293d0d9d47f01d982b0b

**Comment by jostyee** [comment]
Removed TrailingSpaces & GoGuru plugins, restarted ST3 & then install GoGuru 0.1.8, still not working.

```
GoGuru: ('debug:', True)
GoGuru: ('use_golangconfig', False)
GoGuru [DEBUG]: ("couldn't get git tag:", <class 'NotADirectoryError'>)
GoGuru: ('version:', '0.1.8')
GoRename: ('debug:', False)
GoRename: ('use_golangconfig', False)
GoRename: ('version:', '0.1.5')

...GoSublime logs

Package Control: Skipping automatic upgrade, last run at 2016-05-19 11:47:15, next run at 2016-05-19 12:47:15 or after
Unable to open /Users/me/Library/Application Support/Sublime Text 3/Packages/GoGuru/Default (OSX).sublime-keymap
```

There's no `GoGuru` folder in `Packages` here.

**Comment by jostyee** [comment]
Upgraded to 0.1.9

```
Unable to open /Users/me/Library/Application Support/Sublime Text 3/Packages/GoGuru/Default.sublime-settings
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 574, in run_
    return self.run(edit)
  File "goGuru in /Users/me/Library/Application Support/Sublime Text 3/Installed Packages/GoGuru.sublime-package", line 102, in run
KeyError: -1
```

my user settings of GoGuru:

``` json
{
    "goguru_debug": true,
    "env": { "GOPATH": "$HOME/go/bin:$PATH" }
}
```

**Comment by alvarolm** [comment]
**Do you have any files at "/Users/me/Library/Application Support/Sublime Text 3/Packages/GoGuru/" ?, if so delete them, including their parent directory "GoGuru"**

please paste the output of:
`ls /Users/me/Library/Application Support/Sublime Text 3/Packages/GoGuru/`

**Comment by jostyee** [comment]
There's no GoGuru folder at /Users/me/Library/Application Support/Sublime Text 3/Packages/

**Comment by alvarolm** [comment]
before invoking GoGuru the cursor needs to be over the identifier(variable, function, ...) you wanna query, and the file needs to be stored.

**Comment by alvarolm** [comment]
starting at version **0.1.11** you should see an error message when GoGuru couldn't get the cursor position.
besides I recommend you to reinstall and update sublime to the latest build (3114 at the time)

**Comment by ardan-bkennedy** [comment]
I am running ST3 3114 with version 0.1.12.  I am getting the same thing. It says it is running the command but nothing. I also tried the debug mode. Wondering if there are path related settings I am missing?

**Comment by alvarolm** [comment]
@ardan-bkennedy

by default will import the shell env vars, so if its working on your shell the plugin should be working too

it would be useful to inspect the debug logs anyway, with out that I cant do more, sorry guys.

**Comment by ardan-bkennedy** [comment]
I wish there was debug information to show. It just says it is running and I get nothing else :(

I was really hoping this would work. I have to set my GOPATH in the GoSublime settings even though I do have my environment set. But thanks for working on this!!

**Comment by ChrisHines** [comment]
@ardan-bkennedy Have you looked in the Sublime console for the debug log? Use ctrl/cmd+` to open the console view.

**Comment by ardan-bkennedy** [comment]
Thanks. I didn't know about that. Will do ASAP. Brilliant

**Comment by jostyee** [comment]
@alvarolm upgrading to 0.1.12, the popup shows but after click `definition` it hangs

```
Running guru definition command...
```

debug log:

```
GoGuru [DEBUG]: ('env', {'USER': 'me', 'TMPDIR': '/var/folders/wy/p4jgcm2s0417ptf5_6hppnfw0000gn/T/', 'HOME': '/Users/me', 'PATH': '/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin', 'XPC_FLAGS': '0x0', 'Apple_PubSub_Socket_Render': '/private/tmp/com.apple.launchd.2ojkIsgLrs/Render', 'SHLVL': '1', 'SHELL': '/bin/zsh', 'PWD': '/Applications/Sublime Text.app/Contents/MacOS', '__CF_USER_TEXT_ENCODING': '0x1F5:0x0:0x0', 'SSH_AUTH_SOCK': '/private/tmp/com.apple.launchd.j3RKjdNwWi/Listeners', 'XPC_SERVICE_NAME': '0', '_': '/usr/bin/env', 'SECURITYSESSIONID': '186a8', 'OLDPWD': '/Applications/Sublime Text.app/Contents/MacOS', 'LOGNAME': 'me'})
Traceback (most recent call last):
  File "goGuru in /Users/me/Library/Application Support/Sublime Text 3/Installed Packages/GoGuru.sublime-package", line 123, in on_done
  File "goGuru in /Users/me/Library/Application Support/Sublime Text 3/Installed Packages/GoGuru.sublime-package", line 219, in guru
KeyError: 'GOPATH'
```

whether specify `GOPATH` env in goguru settings file or not doesn't work.

**Comment by jostyee** [comment]
the FileNotFoundError is still there:

```
Unable to open /Users/me/Library/Application Support/Sublime Text 3/Packages/GoGuru/Default.sublime-settings
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 231, in run_callback
    expr()
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 327, in <lambda>
    run_callback('on_activated', callback, lambda: callback.on_activated(v))
  File "trailing_spaces in /Users/me/Library/Application Support/Sublime Text 3/Installed Packages/TrailingSpaces.sublime-package", line 419, in on_activated
  File "trailing_spaces in /Users/me/Library/Application Support/Sublime Text 3/Installed Packages/TrailingSpaces.sublime-package", line 440, in freeze_last_version
  File "./python3.3/codecs.py", line 896, in open
FileNotFoundError: [Errno 2] No such file or directory: '/Users/me/Library/Application Support/Sublime Text 3/Packages/GoGuru/Default.sublime-settings'
```

**Comment by ilearnio** [comment]
Having same issue on Mac. When in the user config I have only `"goguru_debug": true` I'm getting this:

```
GoGuru [DEBUG]: ('cmd_env', {'_system_version': '10.12', '_system_type': 'Darwin', 'GEM_HOME': '/Users/Admin/.rvm/gems/ruby-2.2.4', 'USER': 'Admin', 'rvm_version': '1.29.2 (latest)', 'XPC_FLAGS': '0x0', 'rvm_path': '/Users/Admin/.rvm', '__CF_USER_TEXT_ENCODING': '0x1F5:0x0:0x0', 'SHELL': '/bin/zsh', 'MY_RUBY_HOME': '/Users/Admin/.rvm/rubies/ruby-2.2.4', 'SSH_AUTH_SOCK': '/private/tmp/com.apple.launchd.wAqMXs0mso/Listeners', 'OLDPWD': '/Applications/Sublime Text.app/Contents/MacOS', 'IRBRC': '/Users/Admin/.rvm/rubies/ruby-2.2.4/.irbrc', 'GEM_PATH': '/Users/Admin/.rvm/gems/ruby-2.2.4:/Users/Admin/.rvm/gems/ruby-2.2.4@global', 'HOME': '/Users/Admin', '_': '/usr/bin/env', 'XPC_SERVICE_NAME': '0', '_system_arch': 'x86_64', 'TMPDIR': '/var/folders/jj/v42qp0j905z3r5bc8phm_11r0000gn/T/', 'Apple_PubSub_Socket_Render': '/private/tmp/com.apple.launchd.dBf7u5IwPn/Render', 'SHLVL': '1', 'PATH': '/Users/Admin/.rvm/gems/ruby-2.2.4/bin:/Users/Admin/.rvm/gems/ruby-2.2.4@global/bin:/Users/Admin/.rvm/rubies/ruby-2.2.4/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/Admin/.rvm/gems/ruby-2.2.4/bin:/Users/Admin/.rvm/gems/ruby-2.2.4@global/bin:/Users/Admin/.rvm/rubies/ruby-2.2.4/bin:/Users/Admin/.rvm/bin', 'rvm_prefix': '/Users/Admin', 'RUBY_VERSION': 'ruby-2.2.4', 'LOGNAME': 'Admin', 'rvm_bin_path': '/Users/Admin/.rvm/bin', '_system_name': 'OSX', 'PWD': '/Applications/Sublime Text.app/Contents/MacOS'})
GoGuru [DEBUG]: ('goguru_env', {})
GoGuru [DEBUG]: ('final_env', {'_system_version': '10.12', '_system_type': 'Darwin', 'GEM_HOME': '/Users/Admin/.rvm/gems/ruby-2.2.4', 'USER': 'Admin', 'rvm_version': '1.29.2 (latest)', 'XPC_FLAGS': '0x0', 'rvm_path': '/Users/Admin/.rvm', '__CF_USER_TEXT_ENCODING': '0x1F5:0x0:0x0', 'SHELL': '/bin/zsh', 'MY_RUBY_HOME': '/Users/Admin/.rvm/rubies/ruby-2.2.4', 'SSH_AUTH_SOCK': '/private/tmp/com.apple.launchd.wAqMXs0mso/Listeners', 'OLDPWD': '/Applications/Sublime Text.app/Contents/MacOS', 'IRBRC': '/Users/Admin/.rvm/rubies/ruby-2.2.4/.irbrc', 'GEM_PATH': '/Users/Admin/.rvm/gems/ruby-2.2.4:/Users/Admin/.rvm/gems/ruby-2.2.4@global', 'HOME': '/Users/Admin', '_': '/usr/bin/env', 'XPC_SERVICE_NAME': '0', '_system_arch': 'x86_64', 'TMPDIR': '/var/folders/jj/v42qp0j905z3r5bc8phm_11r0000gn/T/', 'Apple_PubSub_Socket_Render': '/private/tmp/com.apple.launchd.dBf7u5IwPn/Render', 'SHLVL': '1', 'PATH': '/Users/Admin/.rvm/gems/ruby-2.2.4/bin:/Users/Admin/.rvm/gems/ruby-2.2.4@global/bin:/Users/Admin/.rvm/rubies/ruby-2.2.4/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/Admin/.rvm/gems/ruby-2.2.4/bin:/Users/Admin/.rvm/gems/ruby-2.2.4@global/bin:/Users/Admin/.rvm/rubies/ruby-2.2.4/bin:/Users/Admin/.rvm/bin', 'rvm_prefix': '/Users/Admin', 'RUBY_VERSION': 'ruby-2.2.4', 'LOGNAME': 'Admin', 'rvm_bin_path': '/Users/Admin/.rvm/bin', '_system_name': 'OSX', 'PWD': '/Applications/Sublime Text.app/Contents/MacOS'})
GoGuru [DEBUG]: ('goguru_use_current_package', True)
Traceback (most recent call last):
  File "goGuru in /Users/Admin/Library/Application Support/Sublime Text 3/Installed Packages/GoGuru.sublime-package", line 159, in on_done
  File "goGuru in /Users/Admin/Library/Application Support/Sublime Text 3/Installed Packages/GoGuru.sublime-package", line 361, in guru
KeyError: 'GOPATH'
```

When I set `"goguru_env": { "GOPATH": "/users/Admin/gocode" }` it gives some more debug info, but still not working:

```
GoGuru [DEBUG]: ('cmd_env', {'_system_version': '10.12', '_system_type': 'Darwin', 'GEM_HOME': '/Users/Admin/.rvm/gems/ruby-2.2.4', 'USER': 'Admin', 'rvm_version': '1.29.2 (latest)', 'XPC_FLAGS': '0x0', 'rvm_path': '/Users/Admin/.rvm', '__CF_USER_TEXT_ENCODING': '0x1F5:0x0:0x0', 'SHELL': '/bin/zsh', 'MY_RUBY_HOME': '/Users/Admin/.rvm/rubies/ruby-2.2.4', 'SSH_AUTH_SOCK': '/private/tmp/com.apple.launchd.wAqMXs0mso/Listeners', 'OLDPWD': '/Applications/Sublime Text.app/Contents/MacOS', 'IRBRC': '/Users/Admin/.rvm/rubies/ruby-2.2.4/.irbrc', 'GEM_PATH': '/Users/Admin/.rvm/gems/ruby-2.2.4:/Users/Admin/.rvm/gems/ruby-2.2.4@global', 'HOME': '/Users/Admin', '_': '/usr/bin/env', 'XPC_SERVICE_NAME': '0', '_system_arch': 'x86_64', 'TMPDIR': '/var/folders/jj/v42qp0j905z3r5bc8phm_11r0000gn/T/', 'Apple_PubSub_Socket_Render': '/private/tmp/com.apple.launchd.dBf7u5IwPn/Render', 'SHLVL': '1', 'PATH': '/Users/Admin/.rvm/gems/ruby-2.2.4/bin:/Users/Admin/.rvm/gems/ruby-2.2.4@global/bin:/Users/Admin/.rvm/rubies/ruby-2.2.4/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/Admin/.rvm/gems/ruby-2.2.4/bin:/Users/Admin/.rvm/gems/ruby-2.2.4@global/bin:/Users/Admin/.rvm/rubies/ruby-2.2.4/bin:/Users/Admin/.rvm/bin', 'rvm_prefix': '/Users/Admin', 'RUBY_VERSION': 'ruby-2.2.4', 'LOGNAME': 'Admin', 'rvm_bin_path': '/Users/Admin/.rvm/bin', '_system_name': 'OSX', 'PWD': '/Applications/Sublime Text.app/Contents/MacOS'})
GoGuru [DEBUG]: ('goguru_env', {'GOPATH': '/users/Admin/gocode'})
GoGuru [DEBUG]: ('final_env', {'_system_version': '10.12', '_system_type': 'Darwin', 'GEM_HOME': '/Users/Admin/.rvm/gems/ruby-2.2.4', 'USER': 'Admin', 'rvm_version': '1.29.2 (latest)', 'XPC_FLAGS': '0x0', 'rvm_path': '/Users/Admin/.rvm', '__CF_USER_TEXT_ENCODING': '0x1F5:0x0:0x0', 'SHELL': '/bin/zsh', 'MY_RUBY_HOME': '/Users/Admin/.rvm/rubies/ruby-2.2.4', 'SSH_AUTH_SOCK': '/private/tmp/com.apple.launchd.wAqMXs0mso/Listeners', 'OLDPWD': '/Applications/Sublime Text.app/Contents/MacOS', 'IRBRC': '/Users/Admin/.rvm/rubies/ruby-2.2.4/.irbrc', 'GOPATH': '/users/Admin/gocode', 'GEM_PATH': '/Users/Admin/.rvm/gems/ruby-2.2.4:/Users/Admin/.rvm/gems/ruby-2.2.4@global', 'HOME': '/Users/Admin', '_': '/usr/bin/env', 'XPC_SERVICE_NAME': '0', '_system_arch': 'x86_64', 'TMPDIR': '/var/folders/jj/v42qp0j905z3r5bc8phm_11r0000gn/T/', 'Apple_PubSub_Socket_Render': '/private/tmp/com.apple.launchd.dBf7u5IwPn/Render', 'SHLVL': '1', 'PATH': '/Users/Admin/.rvm/gems/ruby-2.2.4/bin:/Users/Admin/.rvm/gems/ruby-2.2.4@global/bin:/Users/Admin/.rvm/rubies/ruby-2.2.4/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/Admin/.rvm/gems/ruby-2.2.4/bin:/Users/Admin/.rvm/gems/ruby-2.2.4@global/bin:/Users/Admin/.rvm/rubies/ruby-2.2.4/bin:/Users/Admin/.rvm/bin', 'rvm_prefix': '/Users/Admin', 'RUBY_VERSION': 'ruby-2.2.4', 'LOGNAME': 'Admin', 'rvm_bin_path': '/Users/Admin/.rvm/bin', '_system_name': 'OSX', 'PWD': '/Applications/Sublime Text.app/Contents/MacOS'})
GoGuru [DEBUG]: ('goguru_use_current_package', True)
GoGuru [DEBUG]: ('GOPATH', '/users/Admin/gocode/src')
GoGuru [DEBUG]: ('local_package', '../../../../Users/Admin/gocode/src/github.com/ilearnio/hello')
GoGuru [DEBUG]: ('guru_scope', ',../../../../Users/Admin/gocode/src/github.com/ilearnio/hello')
GoGuru [DEBUG]: ('cmd', 'guru -scope ,../../../../Users/Admin/gocode/src/github.com/ilearnio/hello -tags ""  definition /Users/Admin/gocode/src/github.com/ilearnio/hello/main.go:#80')
GoGuru [ERROR]: ('/bin/sh: guru: command not found\n',)
```

Also tried to set it to `/users/Admin/gocode/bin`, `$HOME/gocode/bin:$PATH`, `/users/Admin/gocode/bin:$PATH`, `/users/Admin/gocode:$PATH` with no luck.

**Comment by ilearnio** [comment]
Just found a quick workaround to this by adding a symlink `ln -s /Users/Admin/gocode/bin/guru /usr/local/bin` and now it is working! Thx!
